# Generated by Django 2.1.5 on 2019-01-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('C', 'Client'), ('P', 'Provider'), ('E', 'Employee')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='contacts/pictures')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Country')),
            ],
        ),
    ]
